version: '3'
services:
  app:
    container_name: 'kah-api'
    build:
      context: ./
      dockerfile: environment/dockerfiles/app.dockerfile
      args:
        xdebug: 'true'
        tinker: 'true'
    user: '1000:1000'
    volumes:
      - './:/var/www:delegated'
    env_file:
      - environment/docker.env
    ports:
      - '9000:9000'
  web:
    container_name: 'kah-web'
    build:
      context: ./
      dockerfile: environment/dockerfiles/web.dockerfile
    environment:
      - FAST_CGI_HOST=app
    volumes:
      - './:/var/www:delegated'
    ports:
      - '8080:80'
  database:
    container_name: 'kah-db'
    image: 'postgres:latest'
    volumes:
      - '/var/dbData:/var/lib/postgresql/data'
    ports:
      - '3307:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kards-against-humanity
  testdatabase:
    container_name: 'kah-test-db'
    image: 'postgres:latest'
    volumes:
      - '/var/dbDatatest:/var/lib/postgresql/data'
    ports:
      - '33071:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kards-against-humanity
volumes:
  dbData: null
  dbDatatest: null
