name: Build and Test

on:
  pull_request:
    branches: [master, develop]
    paths-ignore:
      - "**/*.md"
      - "*.md"

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0.3'
      - name: Copy .env.example to .env
        run: cp .env.example .env
      - name: Copy .docker.env.example to .docker.env
        run: cp environment/.docker.env.example environment/docker.env
      - run: docker-compose pull
      - name: make vendor folder placeholder
        run: mkdir vendor
      - name: Spin up container
        run: docker-compose up -d
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Fix Permissions
        run: chmod -R 777 ./
      - name: Generate Application Key
        run: docker-compose exec -T app php artisan key:generate
      - name: Run migrations
        run: docker-compose exec -T app php artisan migrate:fresh --force
      - name: Run Seeders
        run: docker-compose exec -T app php artisan db:seed --force
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: docker-compose exec -T app vendor/bin/phpunit
      - name: Spin down container
        if: always()
        run: docker-compose down -v

